import random
from datetime import datetime, timedelta

# Feedback samples
positive_feedbacks = [
    "The noodles were delicious and flavorful!",
    "Great service, I really enjoyed the meal.",
    "Loved the spice level, just perfect.",
    "Very friendly staff and cozy atmosphere.",
    "Quick service and tasty food, highly recommended!",
    "The soup base was rich and satisfying.",
    "Great value for money, I’ll be back soon.",
    "The noodle texture was spot on.",
    "Absolutely loved the broth, so comforting.",
    "Staff were polite and attentive throughout.",
    "The food came out hot and fresh.",
    "Perfect portion sizes, not too heavy.",
    "Affordable prices for such high quality.",
    "The dumplings were soft and tasty.",
    "A wonderful dining experience overall.",
    "The restaurant is always clean and inviting.",
    "The spice balance was excellent.",
    "Loved the variety of toppings offered.",
    "The noodles tasted homemade and authentic.",
    "I appreciate the quick turnaround time.",
    "My order was accurate and delicious.",
    "I felt very welcomed by the staff.",
    "The soup was hearty and flavorful.",
    "They accommodated my spice request perfectly.",
    "The presentation of the food was beautiful.",
    "Really enjoyed the fresh vegetables in the dish.",
    "Perfect place for a casual meal.",
    "The atmosphere is calm and relaxing.",
    "The seasoning was perfectly balanced.",
    "The noodles didn’t feel greasy at all.",
    "The flavors were bold yet comforting.",
    "Staff checked in to make sure I was satisfied.",
    "It’s my favorite spot for noodles now.",
    "Loved the rich umami flavor in the broth.",
    "Everything was served quickly and neatly.",
    "The side dishes complemented the noodles so well.",
    "I enjoyed every bite of my meal.",
    "The freshness of the ingredients stood out.",
    "I was impressed by the attention to detail.",
    "They handled the rush hour very well.",
    "The soy-based broth was fantastic.",
    "The flavors were well-balanced and light.",
    "The restaurant has a warm, welcoming vibe.",
    "Excellent value for such generous portions.",
    "The noodles had the perfect chewiness.",
    "This place never disappoints!",
    "The food exceeded my expectations.",
    "Highly consistent taste every time I visit.",
    "The noodles were rich with flavor.",
    "Customer service is top-notch here.",
    "I enjoyed the peaceful ambiance.",
    "The broth had a nice depth of flavor.",
    "Very satisfying meal, left me full and happy.",
    "The garnishes were fresh and well chosen.",
    "The chili oil added just the right kick.",
    "The staff made me feel at home.",
    "The restaurant is beautifully decorated.",
    "The egg in the ramen was perfectly cooked.",
    "I loved the tender meat in the noodles.",
    "The food came faster than I expected.",
    "Every bite was a treat.",
    "It’s my go-to spot for comfort food.",
    "The noodles were perfectly cooked al dente.",
    "The flavor profile was very authentic.",
    "Very family-friendly environment.",
    "They have amazing vegetarian options too.",
    "The broth warmed me up instantly.",
    "The pickled veggies were a great touch.",
    "I left with a big smile on my face.",
    "The noodles had just the right bounce.",
    "Very fresh and delicious every single time.",
    "The chefs clearly know their craft.",
    "The garlic flavor came through beautifully.",
    "Very generous with the toppings.",
    "Loved the sesame oil aroma in the dish.",
    "The presentation was simple yet elegant.",
    "I enjoyed the crispy texture of the add-ons.",
    "The miso broth was absolutely delightful.",
    "This place is a hidden gem.",
    "The consistency in flavor is impressive.",
    "They always serve piping hot food.",
    "Loved the refreshing iced tea with the meal.",
    "Every visit feels like a treat.",
    "The staff offered great recommendations.",
    "Very reasonable prices for such quality food.",
    "I could eat here every week.",
    "The noodles are truly addictive!",
    "The spicy broth was my favorite part.",
    "Everything tasted fresh and natural.",
    "The soy sauce blend was on point.",
    "Staff greeted me with a smile.",
    "The restaurant has a cozy atmosphere.",
    "Loved how clean and organized the place is.",
    "The broth had layers of complex flavor.",
    "The meal was filling without being too heavy.",
    "I enjoyed the peaceful background music.",
    "The extra toppings made it even better.",
    "Their takeout packaging is neat and secure.",
    "The food was worth every penny.",
    "My friends and I had a great time here.",
    "The noodles soaked up the broth perfectly.",
    "Always a pleasure dining here.",
    "The flavor combinations were outstanding.",
    "I recommend this restaurant to everyone."
]

negative_feedbacks = [
    "The noodles were too salty.",
    "Service was very slow.",
    "The portion size felt too small for the price.",
    "The soup tasted bland.",
    "My order was served cold.",
    "The noodles were overcooked and mushy.",
    "I found a hair in my food.",
    "The staff seemed unfriendly.",
    "The restaurant was too noisy.",
    "It took forever to get seated.",
    "The broth lacked depth of flavor.",
    "The noodles were clumpy.",
    "The vegetables didn’t feel fresh.",
    "The place wasn’t very clean.",
    "I felt the price was too high.",
    "The service felt rushed and inattentive.",
    "The dish was way too oily.",
    "I didn’t like the seasoning balance.",
    "The menu felt too limited.",
    "The noodles had a weird aftertaste.",
    "The table was sticky when I sat down.",
    "They messed up my order.",
    "The wait time was unacceptable.",
    "The presentation of the food was sloppy.",
    "The staff ignored my request.",
    "The air conditioning wasn’t working well.",
    "The food wasn’t served hot enough.",
    "The chili sauce was overpowering.",
    "The meat was tough and chewy.",
    "The broth was watery and lacked richness.",
    "The noodles were stuck together.",
    "The overall taste was disappointing.",
    "The service was rude.",
    "The food arrived late.",
    "The chairs were uncomfortable.",
    "The flavors didn’t match well.",
    "The dish didn’t look appetizing.",
    "The portion was inconsistent.",
    "The noodles lacked seasoning.",
    "I didn’t feel welcomed.",
    "The bill was incorrect.",
    "I expected more variety on the menu.",
    "The food wasn’t fresh.",
    "The restaurant smelled unpleasant.",
    "The soup was too spicy.",
    "The noodles had no flavor.",
    "The side dishes were stale.",
    "The meat was undercooked.",
    "The place was overcrowded.",
    "The staff wasn’t attentive enough.",
    "The noodles were soggy.",
    "I didn’t get enough sauce.",
    "The broth had a burnt taste.",
    "It was too expensive for what I got.",
    "The noodles were rubbery.",
    "The food tasted reheated.",
    "The service was careless.",
    "The noodles didn’t taste authentic.",
    "The waiters didn’t check on us.",
    "The food was too greasy.",
    "The order was incomplete.",
    "The soup was lukewarm.",
    "The rice was undercooked.",
    "The noodles lacked texture.",
    "The music was too loud.",
    "The drinks were watered down.",
    "The food had too much MSG.",
    "The noodles were too thick.",
    "The broth was overly salty.",
    "The waiting area was too small.",
    "The restaurant was understaffed.",
    "The dish tasted burnt.",
    "The vegetables were soggy.",
    "The noodles were sticky.",
    "The portion was not filling.",
    "The food lacked freshness.",
    "The staff forgot our drinks.",
    "The order was wrong twice.",
    "The tableware wasn’t clean.",
    "The soup was bitter.",
    "The noodles were bland and boring.",
    "The restaurant was too hot.",
    "The chopsticks were dirty.",
    "The food didn’t taste fresh.",
    "The broth was weak.",
    "The noodles were too chewy.",
    "The meat portion was tiny.",
    "The menu was overpriced.",
    "The waiter was inattentive.",
    "The food was disappointing overall.",
    "The dessert wasn’t fresh.",
    "The noodles were flavorless.",
    "The place felt unhygienic.",
    "The chairs were dirty.",
    "The broth was cold.",
    "The food wasn’t worth the money.",
    "The noodles were soggy and limp.",
    "The meat was dry.",
    "The flavors didn’t blend well.",
    "The staff didn’t apologize for mistakes.",
    "The restaurant was understaffed.",
    "The broth had no depth.",
    "The noodles were tough.",
    "The service felt rushed.",
    "The food took too long to prepare.",
    "The staff seemed uninterested.",
    "The meat had too much fat.",
    "The food wasn’t hot when served.",
    "The noodles were sticky and unappetizing.",
    "The soup lacked flavor.",
    "The portion was unsatisfying.",
    "The atmosphere wasn’t comfortable.",
    "The food didn’t taste fresh.",
    "The rice was soggy.",
    "The staff didn’t listen properly.",
    "The dish was tasteless.",
    "The noodles were soggy and flavorless.",
    "The broth was too watery.",
    "The table service was chaotic.",
    "The food didn’t live up to the hype.",
    "The restaurant was too crowded.",
    "The noodles were clumpy and overcooked.",
    "The food was underwhelming.",
    "The flavors didn’t stand out.",
    "The restaurant was noisy and chaotic.",
    "The broth had a strange taste.",
    "The food was greasy and heavy.",
    "The noodles were stale.",
    "The staff forgot part of my order.",
    "The soup was over-salted.",
    "The noodles had an odd texture.",
    "The service wasn’t friendly.",
    "The food was bland and uninspiring.",
    "The restaurant was poorly ventilated.",
    "The noodles were unappealing.",
    "The broth was disappointing.",
    "The staff didn’t handle complaints well.",
    "The food lacked quality.",
    "The noodles were sloppy.",
    "The wait was too long for simple dishes.",
    "The broth was tasteless.",
    "The food was overpriced and disappointing.",
    "The noodles had a rubbery texture.",
    "The service was unprofessional.",
    "The table was not cleaned properly.",
    "The broth didn’t have enough flavor.",
    "The noodles were bland with no seasoning.",
    "The food didn’t look appetizing.",
    "The staff was inattentive and slow.",
    "The restaurant was uncomfortably hot.",
    "The soup was too thin.",
    "The noodles weren’t fresh.",
    "The portion was too small for the price.",
    "The food wasn’t served properly.",
    "The noodles were too dry.",
    "The meat was bland.",
    "The broth was too salty and thin.",
    "The food was below average.",
    "The noodles tasted artificial.",
    "The rice tasted old.",
    "The staff was disorganized.",
    "The soup didn’t taste good.",
    "The noodles were not enjoyable.",
    "The food felt cheap.",
    "The dish was greasy and heavy.",
    "The noodles were clumpy and dry.",
    "The service lacked professionalism.",
    "The broth was weak and watery.",
    "The restaurant lacked cleanliness.",
    "The noodles had no distinct flavor.",
    "The food was unsatisfying.",
    "The broth was too oily.",
    "The noodles weren’t worth the price.",
    "The food was average at best.",
    "The service was careless and slow.",
    "The noodles tasted bland.",
    "The food wasn’t worth coming back for.",
    "The restaurant felt dirty.",
    "The soup didn’t taste fresh.",
    "The noodles were unappealing.",
    "The dish wasn’t filling enough.",
    "The broth had too much oil.",
    "The food wasn’t impressive.",
    "The noodles were sloppy and bland.",
    "The soup was flavorless.",
    "The service was chaotic.",
    "The noodles didn’t taste good.",
    "The broth lacked seasoning.",
    "The food quality was poor.",
    "The noodles were a letdown.",
    "The restaurant wasn’t clean enough.",
    "The service was rude and careless.",
    "The noodles were disappointing.",
    "The broth had no real flavor.",
    "The food was bland and greasy.",
    "The service was inconsistent.",
    "The noodles were boring.",
    "The dish didn’t meet expectations.",
    "The broth was watery and salty.",
    "The food was flavorless.",
    "The noodles were plain and dry.",
    "The service wasn’t efficient.",
    "The restaurant was too loud.",
    "The broth was disappointing and bland.",
    "The noodles weren’t enjoyable.",
    "The food was greasy and underwhelming.",
    "The soup was tasteless.",
    "The noodles were unsatisfying.",
    "The broth was weak and bland.",
    "The service was poor overall.",
    "The noodles lacked taste.",
    "The food was unappealing.",
    "The broth was oily and salty.",
    "The restaurant lacked good hygiene.",
    "The noodles didn’t taste authentic.",
    "The food wasn’t enjoyable.",
    "The broth wasn’t good.",
    "The noodles were flavorless and mushy.",
    "The food lacked proper seasoning.",
    "The service was not friendly.",
    "The broth was plain and thin.",
    "The noodles were too plain.",
    "The food wasn’t fresh enough.",
    "The broth was weak and flavorless.",
    "The noodles were not cooked well.",
    "The service was very poor.",
    "The food didn’t taste great.",
    "The broth lacked character.",
    "The noodles were sticky and bland.",
    "The restaurant felt unhygienic.",
    "The broth was too greasy.",
    "The noodles were dry and plain.",
    "The food was under-seasoned.",
    "The service was unpleasant.",
    "The broth was unimpressive.",
    "The noodles didn’t taste fresh.",
    "The food lacked effort.",
    "The broth was bland and thin.",
    "The noodles were not tasty.",
    "The food was disappointing overall.",
    "The service wasn’t helpful.",
    "The broth had little flavor.",
    "The noodles tasted dull.",
    "The food was unimpressive.",
    "The broth was too plain.",
    "The noodles were sloppy and unflavored.",
    "The restaurant was dirty.",
    "The broth wasn’t satisfying.",
    "The noodles were not worth it.",
    "The food was forgettable.",
    "The broth was weak and unsatisfying."
]


neutral_feedbacks = [
    "The portion sizes are fair.",
    "It was an average experience overall.",
    "The ambiance is okay, nothing special.",
    "Food was fine but nothing memorable.",
    "The price is reasonable compared to others.",
    "Seating was decent but a bit cramped.",
    "The wait time was acceptable.",
    "The flavors were okay but not unique."
]

# Function to generate random datetime between two dates
def random_date(start, end):
    delta = end - start
    random_seconds = random.randint(0, int(delta.total_seconds()))
    return start + timedelta(seconds=random_seconds)

# Date range
start_date = datetime(2023, 1, 1, 0, 0, 0)
end_date = datetime(2025, 8, 16, 23, 59, 59)

# Generate dataset
dataset = []
for _ in range(1000):  # change 50 to however many feedbacks you want
    feedback_type = random.choice(["Positive", "Negative", "Neutral"])
    if feedback_type == "Positive":
        feedback = random.choice(positive_feedbacks)
    elif feedback_type == "Negative":
        feedback = random.choice(negative_feedbacks)
    else:
        feedback = random.choice(neutral_feedbacks)

    date_time = random_date(start_date, end_date)
    dataset.append(f"{date_time.strftime('%Y-%m-%d')} |  {feedback_type} | {feedback}")

with open ("feedback.csv", "a+") as file:
    for feedback in dataset:
        feed_back = f"{feedback}\n"
        file.write(feed_back)
print("Generated!")

